version: '3.8'
services:
  back:
    build: .
    ports:
      - "8666:8666"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8666"
    volumes:
      - ./avatars:/app/avatars
      - ./uploads/orders:/app/uploads/orders



  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-azv_motors}"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: