"""empty message

Revision ID: 742700ba8b24
Revises: 
Create Date: 2025-03-26 15:25:03.399647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742700ba8b24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_imei', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('course', sa.Float(), nullable=True),
    sa.Column('last_update_coordinates', sa.DateTime(), nullable=True),
    sa.Column('last_update_sensors', sa.DateTime(), nullable=True),
    sa.Column('is_engine_on', sa.Boolean(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('engine_temperature', sa.Float(), nullable=True),
    sa.Column('is_hood_open', sa.Boolean(), nullable=True),
    sa.Column('fuel_level', sa.Float(), nullable=True),
    sa.Column('engine_hours', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('vehicle_imei')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
