"""empty message

Revision ID: f28e98ff9ce4
Revises: 1ac444a8a0fe
Create Date: 2025-06-26 23:53:34.532969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28e98ff9ce4'
down_revision: Union[str, None] = '1ac444a8a0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('plate_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'vehicles', ['plate_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_column('vehicles', 'plate_number')
    # ### end Alembic commands ###
